### PR TITLE
feat(tf2-competitive): add FBTF.tf config files

### PR DESCRIPTION
**Pull request by galdoway**
The purpose of this pull request is to add the configurations and whitelist of the Brazilian TF2 league automatically as it is done for the other configurations.
- The version number is based on the [current edition of the league,](https://fbtf.tf/forums/threads/241) in this case it is number 23.
- The files are downloaded from the official [FBTF ](https://fbtf.tf/) website.
- They are moved to the corresponding folder and then the zip file is deleted.

Let me know if I should modify anything or if you have any other suggestions :)

### CODE REVIEW

**Comment by garrappachc** [comment]
Looks good :)
The only thing missing is the md5 checksum. Add it to the [checksum.md5 file](https://github.com/melkortf/tf2-servers/blob/master/packages/tf2-competitive/checksum.md5).

**Review by garrappachc — CHANGES_REQUESTED** [review]
Add fbtf_cfg_s23.zip md5 checksum

**Comment by galdoway** [comment]
> Add fbtf_cfg_s23.zip md5 checksum

Done!
Let me know if I have to change something else.

**Review by garrappachc — APPROVED** [review]

**Comment by garrappachc** [comment]
Look good!

**Pull request merged**
